{{- $chartName := include "gateway.name" . -}}
{{- $tracingUrl := include "gateway.tracingUrl" . -}}
{{- $metricsUrl := include "gateway.metricsUrl" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{-  $ca := (include "common.ca.merged" . ) | fromYaml }}
  {{- if $ca.enabled }}
  REQUESTS_CA_BUNDLE: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  NODE_EXTRA-_CA_CERTS: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  {{- end }}
  LOOKUP_TABLES_URL: {{ .Values.validations.lookupTables.url | quote }}
  LOOKUP_TABLES_SUB_URL: {{ .Values.validations.lookupTables.subUrl | quote }}
  BASE_PATH: {{ tpl .Values.env.basePath . | quote }}
  PERCENTAGE_LIMIT: {{ .Values.validations.percentageLimit | quote }}
  SERVER_PORT: {{ .Values.env.targetPort | quote }}
  STORE_TRIGGER_URL: http://{{ .Release.Name }}-store-trigger
  {{- $storeTrigger := (include "common.store-trigger.merged" . ) | fromYaml }}
  STORE_TRIGGER_SUB_URL: {{ $storeTrigger.subUrl | quote }}
  CATALOG_URL: http://{{ .Release.Name }}-catalog
  {{- $catalog := (include "common.catalog.merged" . ) | fromYaml }}
  CATALOG_SUB_URL: {{ $catalog.subUrl | quote }}
  {{- $providers := (include "common.providers.merged" . ) | fromYaml }}
  {{ if eq $providers.source "NFS" }}
  {{- $NFS := (include "common.NFS.merged" . ) | fromYaml }}
  PV_SOURCE_PATH: {{ $NFS.source.pv_path | quote }}
  {{ end }}
  {{ if eq $providers.destination "S3" }}
  {{- $S3 := (include "common.S3.merged" . ) | fromYaml }}
  S3_DEST_ACCESS_KEY_ID: {{ $S3.accessKey | quote }}
  S3_DEST_SECRET_ACCESS_KEY: {{ $S3.secretAccessKey | quote }}
  S3_DEST_END_POINT_URL: "{{ $S3.serverProto }}://{{ $S3.server }}:{{ $S3.serverPort }}"
  S3_DEST_BUCKET: {{ $S3.bucket | quote }}
  S3_DEST_REGION: {{ $S3.region | quote }}
  S3_DEST_STORAGE_CLASS: {{ $S3.storageClass | quote }} 
  S3_DEST_FORCE_PATH_STYLE: {{ eq $S3.style "path" | ternary "true" "false" | quote }}
  S3_DEST_SSL_ENABLED: {{ $S3.sslEnabled | quote}}
  S3_DEST_MAX_ATTEMPTS: {{ $S3.maxAttempts | quote}}
  {{ end }}