{{- $chartName := include "gateway.name" . -}}
{{- $tracingUrl := include "gateway.tracingUrl" . -}}
{{- $metricsUrl := include "gateway.metricsUrl" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{-  $ca := (include "common.ca.merged" . ) | fromYaml }}
  {{- if $ca.enabled }}
  REQUESTS_CA_BUNDLE: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  NODE_EXTRA-_CA_CERTS: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  {{- end }}
  LOOKUP_TABLES_URL: {{ .Values.validations.lookupTables.url | quote }}
  LOOKUP_TABLES_SUB_URL: {{ .Values.validations.lookupTables.subUrl | quote }}
  BASE_PATH: {{ tpl .Values.env.basePath . | quote }}
  PERCENTAGE_LIMIT: {{ .Values.validations.percentageLimit | quote }}
  SERVER_PORT: {{ .Values.env.targetPort | quote }}
