apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      volumes:
      - name: ingestion-source-storage
        persistentVolumeClaim:
          claimName: {{ .Values.storage.ingestionSourcePvc.name }}
      {{- if .Values.logsFilebeat.enabled }}
      - name: logs
        emptyDir: {}
      - name: config
        configMap:
          name: filebeat-config
      {{- end }}
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        volumeMounts: 
            - name: ingestion-source-storage
              mountPath: {{ .Values.storage.ingestionSourcePv.hostPath }}
            {{- if .Values.logsFilebeat.enabled }}
            - name: logs
              mountPath: {{ .Values.logsFilebeat.mountPath }}
            {{- end }}
        env:
        - name: SERVER_PORT
          value: {{ .Values.service.targetPort | quote }}
        - name: STORE_TRIGGER_URL
          value: {{ tpl .Values.storeTrigger.url . | quote }}
        - name: LOOKUP_TABLES_URL
          value: {{ tpl .Values.lookupTables.url . | quote }}
        - name: LOOKUP_TABLES_SUB_URL
          value: {{ tpl .Values.lookupTables.subUrl . | quote }}
        - name: BASE_PATH
          value: {{ tpl .Values.paths.basePath . | quote }}
        - name: PV_PATH
          value: {{ tpl .Values.storage.ingestionSourcePv.hostPath . | quote }}
        - name: PERCENTAGE_LIMIT
          value: {{ .Values.percentageLimit | quote }}
      {{- if .Values.logsFilebeat.enabled }}
        command: ["/bin/sh", "-c", "node --max_old_space_size=512 ./index.js >> /usr/src/app/logs/log.log 2>&1"]
      - name: filebeat
        image: {{ .Values.logsFilebeat.filebeatImage }}
        args: [ "-c", "/etc/filebeat.yml", "-e" ]
        volumeMounts:
          - name: logs
            mountPath: {{ .Values.logsFilebeat.mountPath }}
          - name: config
            mountPath: /etc/filebeat.yml
            subPath: filebeat.yml
      {{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort | int }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.service.targetPort | int }}
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: {{ .Values.service.targetPort | int }}
