{{- if .Values.storage.ingestionSourcePv.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.ingestionSourcePv.name }}
spec:
  {{- if .Values.storage.ingestionSourcePv.storageClass }}
  storageClassName: {{ .Values.storage.ingestionSourcePv.storageClass }}
  {{- end }}
  capacity:
    storage:  {{ .Values.storage.ingestionSourcePv.size }}
  accessModes:
    - {{ .Values.storage.ingestionSourcePv.accessModes }}
  hostPath:
    path: {{ .Values.storage.ingestionSourcePv.hostPath }}
{{- end }}
