{{- if .Values.storage.ingestionSourcePvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.ingestionSourcePvc.name }}
spec:
  {{- if .Values.storage.ingestionSourcePvc.storageClass }}
  storageClassName: {{ .Values.storage.ingestionSourcePvc.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.ingestionSourcePvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.ingestionSourcePvc.size }}
{{- end }}
