{{- $releaseName := .Release.Name -}}
{{- $chartName := include "gateway.name" . -}}
{{- $cloudProviderFlavor := include "gateway.cloudProviderFlavor" . -}}
{{- $fullNeme := include "gateway.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullNeme }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "gateway.environment" . }}
    release: {{ $releaseName }}
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $fullNeme }}
    {{- include "gateway.selectorLabels" . | nindent 4 }}
