apiVersion: v2
name: gateway
description: A Helm chart for 3D gateway service
version: 2.8.3
appVersion: 2.8.3
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
